### ISSUE TITLE
Compilation Fails on Tests

### ISSUE THREAD

**Issue by firadat** [DNJha/IoTSim-Edge#3]
I would like the authors to guide me how to fix the following error:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.edge.test.ConfigurationTest
{"trace_flag":false,"numUser":1,"ioTDeviceEntities":[{"mobilityEntity":{"movable":true,"volecity":2.0,"range":{"beginX":0,"endX":100},"signalRange":0.0,"location":{"x":0.0,"y":0.0,"z":0.0}},"numberofEntity":0,"assignmentId":1,"ioTClassName":"org.edge.device.iot.TemperatureSensor","iotType":"environmental","name":"temperature","data_frequency":1.0,"dataGenerationTime":1.0,"complexityOfDataPackage":1,"dataSize":1,"networkModelEntity":{"networkType":"wifi","communicationProtocol":"xmpp"},"max_battery_capacity":100.0,"battery_drainage_rate":1.0,"processingAbility":1.0}],"MELEntities":[{"vmid":1,"mips":1111,"size":1111,"ram":1222,"bw":1111,"pesNumber":1,"vmm":"xxx","cloudletSchedulerClassName":"org.cloudbus.cloudsim.CloudletSchedulerTimeShared","datasizeShrinkFactor":0.0}],"broker":{"name":"broker1"},"edgeDatacenter":[{"name":"edgeDatacenter1","characteristics":{"architecture":"x86","os":"Linux","vmm":"Xen","hostListEntities":[{"id":1,"ramProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.RamProvisionerSimple","ramSize":100000},"bwProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.BwProvisionerSimple","bwSize":1000000},"storage":1000000,"peEntities":[{"id":1,"peProvisionerClassName":"org.cloudbus.cloudsim.provisioners.PeProvisionerSimple","mips":100000}],"vmScheduler":{"className":"org.cloudbus.cloudsim.VmSchedulerTimeShared"},"edgeType":"RASPBERRY_PI","geo_location":{"movable":false,"volecity":0.0,"signalRange":50.0,"location":{"x":0.0,"y":0.0,"z":0.0}},"networkModel":{"networkType":"wifi","communicationProtocol":"xmpp"},"max_IoTDevice_capacity":10,"max_battery_capacity":100.0,"battery_drainage_rate":1.0,"current_battery_capacity":100.0},{"id":2,"ramProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.RamProvisionerSimple","ramSize":100000},"bwProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.BwProvisionerSimple","bwSize":1000000},"storage":1000000,"peEntities":[{"id":2,"peProvisionerClassName":"org.cloudbus.cloudsim.provisioners.PeProvisionerSimple","mips":100000}],"vmScheduler":{"className":"org.cloudbus.cloudsim.VmSchedulerTimeShared"},"edgeType":"RASPBERRY_PI","geo_location":{"movable":false,"volecity":0.0,"signalRange":50.0,"location":{"x":100.0,"y":0.0,"z":0.0}},"networkModel":{"networkType":"wifi","communicationProtocol":"xmpp"},"max_IoTDevice_capacity":10,"max_battery_capacity":100.0,"battery_drainage_rate":1.0,"current_battery_capacity":100.0}],"cost":1.0,"timeZone":10.0,"costPerSec":0.0,"costPerMem":0.05,"costPerStorage":0.001,"costPerBw":0.0,"communicationProtocolSupported":["xmpp"],"ioTDeviceClassNameSupported":["org.edge.device.iot.TemperatureSensor"]},"vmAllocationPolicy":{"className":"org.cloudbus.cloudsim.VmAllocationPolicySimple","hostEntities":[{"id":1,"ramProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.RamProvisionerSimple","ramSize":100000},"bwProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.BwProvisionerSimple","bwSize":1000000},"storage":1000000,"peEntities":[{"id":1,"peProvisionerClassName":"org.cloudbus.cloudsim.provisioners.PeProvisionerSimple","mips":100000}],"vmScheduler":{"className":"org.cloudbus.cloudsim.VmSchedulerTimeShared"},"edgeType":"RASPBERRY_PI","geo_location":{"movable":false,"volecity":0.0,"signalRange":50.0,"location":{"x":0.0,"y":0.0,"z":0.0}},"networkModel":{"networkType":"wifi","communicationProtocol":"xmpp"},"max_IoTDevice_capacity":10,"max_battery_capacity":100.0,"battery_drainage_rate":1.0,"current_battery_capacity":100.0},{"id":2,"ramProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.RamProvisionerSimple","ramSize":100000},"bwProvisioner":{"className":"org.cloudbus.cloudsim.provisioners.BwProvisionerSimple","bwSize":1000000},"storage":1000000,"peEntities":[{"id":2,"peProvisionerClassName":"org.cloudbus.cloudsim.provisioners.PeProvisionerSimple","mips":100000}],"vmScheduler":{"className":"org.cloudbus.cloudsim.VmSchedulerTimeShared"},"edgeType":"RASPBERRY_PI","geo_location":{"movable":false,"volecity":0.0,"signalRange":50.0,"location":{"x":100.0,"y":0.0,"z":0.0}},"networkModel":{"networkType":"wifi","communicationProtocol":"xmpp"},"max_IoTDevice_capacity":10,"max_battery_capacity":100.0,"battery_drainage_rate":1.0,"current_battery_capacity":100.0}]},"schedulingInterval":1.0}],"connections":[{"vmId":1,"assigmentIoTId":1}]}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.127 sec
Running org.edge.test.MicroElementTopologyTest
[{"id":0,"downLinkIds":[1,2,3]},{"id":1,"upLinkId":0,"downLinkIds":[3,4]},{"id":2,"upLinkId":0,"downLinkIds":[5,6,7]},{"id":3,"upLinkId":1,"downLinkIds":[]},{"id":4,"upLinkId":1,"downLinkIds":[]},{"id":5,"upLinkId":2,"downLinkIds":[8]},{"id":6,"upLinkId":2,"downLinkIds":[8]},{"id":7,"upLinkId":2,"downLinkIds":[8]},{"id":8,"upLinkId":3,"downLinkIds":[5,6,7]}]
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
convertToClass(org.edge.test.MicroElementTopologyTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.edge.test.MicroElementTopologyTest.convertToClass(MicroElementTopologyTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.edge.test.TestCreateIoTdevice
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
create(org.edge.test.TestCreateIoTdevice)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems: 
	The import org.cloudbus cannot be resolved
	The import org.cloudbus cannot be resolved
	The hierarchy of the type TemperatureSensor is inconsistent
	UtilizationModelFull cannot be resolved to a type
	UtilizationModelFull cannot be resolved to a type
	UtilizationModelFull cannot be resolved to a type
	The method getId() is undefined for the type TemperatureSensor
	SimEvent cannot be resolved to a type
	The method shutdownEntity() of type TemperatureSensor must override or implement a supertype method

	at org.edge.core.iot.TemperatureSensor.<init>(TemperatureSensor.java:3)
	at org.edge.test.TestCreateIoTdevice.createLoTDevice(TestCreateIoTdevice.java:43)
	at org.edge.test.TestCreateIoTdevice.create(TestCreateIoTdevice.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.edge.test.TestState
true
class org.edge.core.iot.TemperatureSensor
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests in error: 
  convertToClass(org.edge.test.MicroElementTopologyTest)
  create(org.edge.test.TestCreateIoTdevice): Unresolved compilation problems: (..)

Tests run: 6, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.775 s
[INFO] Finished at: 2020-04-11T21:33:24+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project simulator: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\faisaliradat\Documents\GitHub\IoTSim-Edge\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by DNJha** [comment]
Hi Firadat,

As I figured out about the first error is you specified **"numberofEntity":0** which initialized 0 IoT devices thus leading to NullPointerException. Have you tried to run the examples without updating? Please send me the details if that will not run successfully.

In terms of build failure, I already told there are some bugs in our program causing this but it does not affect the example execution.

**Comment by firadat** [comment]
Thanks DNJha actually the cloudsim library was not included. The numberofEntity was left to default i.e. 50. I have successfully executed Example 1 and I have attached the output, kindly confirm if it is right so that I can close this issue.

[Sample run.txt](https://github.com/DNJha/IoTSim-Edge/files/4466156/Sample.run.txt)

**Comment by DNJha** [comment]
Good to hear that example is executed successfully. The output attached is also correct.
